---
- name: Do something on OpenStack with Ansible-Inside
  hosts: all

  tasks:
    - debug: var=scvmm_image
    - debug: var=vm_name
    - debug: var=scvmm_host
    - debug: var=scvmm_network

    - name: Create ps1
      template:
        src: "{{ playbook_dir }}/../templates/create-vm.ps1.j2"
        dest: C:\Temp\create-vm.ps1

    - win_shell: C:\Temp\create-vm.ps1

      register: win_shell_out

    - debug:
        var: win_shell_out.stdout_lines